<a href="https://colab.research.google.com/github/rudevico/Gachon-AISTUDY/blob/main/Pytorch_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. tensor data type
* 기본적으로 Machine Learning에서는 연산 속도를 위해서 array data type을 사용한다.
* 이때 Numpy에서는 CPU를 사용하여 array를 연산하기 때문에 DL 수준의 dataset에 대해서 연산하기에는 시간이 많이 소요된다.
* Tensor는 GPU 연산을 지원하는 array이다. pytorch에서는 이를 사용한다.  

> 왜 Numpy ndarray가 아닌, Pytorch tensor를 사용하는지에 대한 자세한 이유들은 이후 실습 과정을 통해서 자연스럽게 알 수 있을 것으로 판단된다.

## 1. 0. Convert list(python) or ndarray(numpy) to tensor(pytorch)

cf. [torch.tensor — PyTorch 2.4 documentation](https://pytorch.org/docs/stable/generated/torch.tensor.html)

```
torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)
```

**Parameters**  
* __data__ - Can be a list, tuple, Numpy `ndarray`, scalar, ...  

**Keyword Arguements**  
* __dtype__(`torch.dtype`, optinal) - the desired data type of returned tensor. default라면, 원본 데이터 타입
* __device__(`torch.device`, optional) - the device of the constructed tensor. defalut라면, 'cpu' 사용, 'cuda'로 설정 시 gpu 사용 가능.
* __requires_grad__(_bool_, optional)
* **pin_memory**(*bool*, optional)

In [1]:
import torch

# case1-1. python list_int
data = [[1, 2, 3], [4, 5, 6]]

x_default = torch.tensor(data)
x_int = torch.tensor(data, dtype=int)
x_int64 = torch.tensor(data, dtype=torch.int64) # default int
x_int32 = torch.tensor(data, dtype=torch.int32)

# pytorch에서는 int ßßdata type의 default를 64bit로 한다
print(x_default.dtype)
print(x_int.dtype)
print(x_int64.dtype)
print(x_int32.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_default)    # default -> no return
print(x_int)        # default -> no return
print(x_int64)      # default -> no return
print(x_int32)      # not default -> return

torch.int64
torch.int64
torch.int64
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [2]:
# case1-2. python list_float
data = [[1, 2, 3], [4, 5, 6]]

x_float = torch.tensor(data, dtype=float)
x_float32 = torch.tensor(data, dtype=torch.float32) # default float
x_float64 = torch.tensor(data, dtype=torch.float64)
x_double = torch.tensor(data, dtype=torch.double)

# pytorch에서는 int data type의 default를 32bit로 한다
print(x_float.dtype)
print(x_float32.dtype) # default float
print(x_float64.dtype)
print(x_double.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_float)      # not default -> return
print(x_float32)    # default -> no return
print(x_float64)    # not default -> return
print(x_double)     # not default -> return

torch.float64
torch.float32
torch.float64
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [3]:
# case2. numpy to tensor
# 결론적으로는 list to tensor나 ndarray to tensor나 동일하다.
import numpy as np
np_data = np.array(data)
print(type(np_data))
print(np_data)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [4]:
# case2-1. numpy ndarray_int
x_default = torch.tensor(np_data)
x_int = torch.tensor(np_data, dtype=int)
x_int64 = torch.tensor(np_data, dtype=torch.int64) # default int
x_int32 = torch.tensor(np_data, dtype=torch.int32)

# pytorch에서는 int data type의 default를 64bit로 한다
print(x_default.dtype)
print(x_int.dtype)
print(x_int64.dtype)
print(x_int32.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_default)    # default -> no return
print(x_int)        # default -> no return
print(x_int64)      # default -> no return
print(x_int32)      # not default -> return

torch.int64
torch.int64
torch.int64
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [5]:
# case2-2. numpy ndarray_float
data = [[1, 2, 3], [4, 5, 6]]

x_float = torch.tensor(np_data, dtype=float)
x_float32 = torch.tensor(np_data, dtype=torch.float32) # default float
x_float64 = torch.tensor(np_data, dtype=torch.float64)
x_double = torch.tensor(np_data, dtype=torch.double)

# pytorch에서는 int data type의 default를 32bit로 한다
print(x_float.dtype)
print(x_float32.dtype) # default float
print(x_float64.dtype)
print(x_double.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_float)      # not default -> return
print(x_float32)    # default -> no return
print(x_float64)    # not default -> return
print(x_double)     # not default -> return

torch.float64
torch.float32
torch.float64
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


## 1. 1. How to use GPU(CUDA)

In [7]:
# torch를 실행중인 device에서 cuda(gpu)를 사용할 수 있는지 확인
cuda_available = torch.cuda.is_available()
print(cuda_available)

True


In [6]:
# torch.tensor() 등으로 tensor를 생성할 때는 default로 'cpu'를 사용
print(x_default.device)

cpu


In [18]:
# CPU에 텐서 생성 (default)
tensor_cpu = torch.tensor([1.0, 2.0, 3.0]) # same as the below
tensor_cpu = torch.tensor([1.0, 2.0, 3.0], device='cpu') # same as the above
print(tensor_cpu.device) # cpu

# GPU에 텐서 생성 (CUDA를 사용할 수 있는 경우)
if torch.cuda.is_available():
    tensor_gpu = torch.tensor([1.0, 2.0, 3.0], device='cuda')
    print(tensor_gpu.device)  # cuda:0
else:
    print('Error: CUDA not available')

cpu
cuda:0


In [19]:
# 기존 텐서를 다른 장치로 이동
tensor_cpu_to_gpu = tensor_cpu.to('cuda')  # CPU에서 GPU로 이동
print(tensor_cpu_to_gpu.device)  # cuda:0

tensor_gpu_to_cpu = tensor_gpu.to('cpu')  # GPU에서 CPU로 이동
print(tensor_gpu_to_cpu.device)  # cpu

cuda:0
cpu


## 1. 2. How to create the tensor

In [39]:
# 1. non-random values

# 1-dim tensor
x = torch.tensor([1, 2, 3])
print(x)
print()

# 2-dim tensor
y = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(y)
print()

# 3-dim tensor, every element is 0
z = torch.zeros((2, 3, 4))
print(z)
print()

# 4-dim tensor, every element is 1
w = torch.ones((2, 2, 2, 2))
print(w)
print()

tensor([1, 2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])



In [76]:
# 2. use the Distribution for random values

# case1. Uniform Distribution
# create 3 by 2 tensor, each element is randomed between [0, 1)
x = torch.rand((3, 2))
print(x)

# case 2. Normal Distribution
# create 2 by 3 tensor, each element is randomed,
# following normal distribution, mean = 0 and deviation = 1
y = torch.randn((2, 3))
print(y)

tensor([[0.5009, 0.5212],
        [0.6158, 0.0122],
        [0.7949, 0.5782]])
tensor([[ 1.9408,  1.0380,  1.5457],
        [-0.7952, -0.2599, -0.0132]])


In [68]:
# 3. randomly-uninitialized values(it is fast because non-intialize)

x = torch.empty(2, 3) # default dtype is float32
print(x)
print(x.dtype)

y = torch.empty(2, 3, dtype=torch.int64) # you can use anoter dtype
print(y)
print(y.dtype)

tensor([[-1.0125e-24,  4.5825e-41, -8.3521e-31],
        [ 3.1124e-41,  0.0000e+00,  0.0000e+00]])
torch.float32
tensor([[     95412690159632,   36028797018963968,      95397799394072],
        [          536870912,   21767388716337664, 7236722170925376883]])
torch.int64


## 1. 3. Convet ndarray to tensor by `.from_numpy()` and `.tensor()`
**1. 0.**에서는 `.tensor()`를 사용해서 numpy array를 tensor로 변환했다.  
`.from_numpy()`로도 변환이 가능한데, 둘의 차이를 알아보자.
```
x_np = np.array([1, 2, 3])
x_tensor = torch.tensor(x_np)
print(type(x_np), type(x_tensor))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
```

```
y_np = np.array([1, 2, 3])
y_tensor = torch.from_numpy(y_np)
print(type(x_np), type(y_tensor))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
```

In [93]:
# `.tensor()`는 call by value 개념이다
# 즉 기존의 ndarray를 copy해서 memory에 별도로 생성한다
# 따라서 tensor와 ndarray는 서로 독립적이다
x_np = np.array([1, 2, 3])
x_tensor = torch.tensor(x_np)
print('ndarray:', x_np[0], 'tensor:', x_tensor[0])

# tesnor의 element를 바꿔도 ndarray에는 영향을 주지 않는다
x_tensor[0] = -1
print('ndarray:', x_np[0], 'tensor:', x_tensor[0])

ndarray: 1 tensor: tensor(1)
ndarray: 1 tensor: tensor(-1)


In [95]:
# `.from_numpy()`는 call by reference 개념이다
# 이미 ndarray가 할당된 memory adress가 존재할 때,
# `.from_numpy()`로 생성된 tensor 객체는 ndarray와 동일한 address를 referencing한다
y_np = np.array([1, 2, 3])
y_tensor = torch.from_numpy(y_np)
print('ndarray:', y_np[0], 'tensor:', y_tensor[0])

# tesnor의 element를 바꾸면 ndarray에도 영향을 준다
y_tensor[0] = -1
print('ndarray:', y_np[0], 'tensor:', y_tensor[0])

# 반대의 경우에도 마찬가지
y_np[1] = -2
print('ndarray:', y_np[1], 'tensor:', y_tensor[1])

ndarray: 1 tensor: tensor(1)
ndarray: -1 tensor: tensor(-1)
ndarray: -2 tensor: tensor(-2)


### 1. 3.(검증) memory address 확인을 통한 검증

In [97]:
# 처음에 내가 아는 선에서 시도한 검증은 다음과 같이 `id()`를 사용하는 것이었다
print(id(x_np), id(x_tensor)) # predict: different  | actual: different
print(id(y_np), id(y_tensor)) # predict: different  | actual: different

140451603101712 140451603761728
140451603101520 140451602993920


> numpy와 tensor 모두 memory address에 value 자체를 보관하고, **그 address를 참조하는 객체**를 생성하는 것이다.  

> 즉 value 자체의 address와 참조하는 객체의 address 두 가지가 존재하는 상태이다.  
이때 `id()`는 후자를 리턴한다.  

> (다음 cell) 다음과 같이 **value 자체의 address**를 확인할 수 있다.

In [100]:
# predict: different    | actual: different
print(x_np.__array_interface__['data'][0])
print(x_tensor.data_ptr())
print()
# predict: same         | actual: same
print(y_np.__array_interface__['data'][0])
print(y_tensor.data_ptr())

95397797441568
95397893097600

95397882517744
95397882517744


## 1. 4. Convert tensor to ndarray
tensor 객체를 Numpy ndarray로 변환하는 method는 `tensor.numpy()` method 뿐이다.  

또한 `tensor.numpy()`는 copy하지 않고, 무조건 share한다.

In [108]:
x_npnp = x_tensor.numpy()
print(type(x_npnp))

y_npnp = y_tensor.numpy()
print(type(y_npnp))

print(x_np.__array_interface__['data'][0])
print(x_tensor.data_ptr()) # x_np를 copy한 x_tensor
print(x_npnp.__array_interface__['data'][0]) # x_tensor를 share한 x_npnp
print()

print(y_np.__array_interface__['data'][0])
print(y_tensor.data_ptr()) # y_np를 share한 y_tensor
print(y_npnp.__array_interface__['data'][0]) # y_tensor를 share한 y_npnp

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
95397797441568
95397893097600
95397893097600

95397882517744
95397882517744
95397882517744


# 2. tensor attributes
Pytorch의 **tensor object**는 많은 attributes를 갖지만, 그 중에서 자주 쓸 만한 것들에 대해서만 다루겠다.  
1. __dtype__
    * data type
2. __device__
    * tensor object가 위치한 device(cpu, gpu)
3. __size__
    * tensor object의 shape
4. __ndim__
    * tensor object의 dimension
5. __numel()__
    * tensor object의 전체 elements 수

In [121]:
# 'dtype', 'device'는 위에서 이미 다뤘으므로 생략함
x = torch.tensor([1, 2, 3, 4])
y = x.view(2, 2) # same as reshape in Numpy

print(y) # [[1, 2], [3, 4]]
print(x.size(), y.size()) # [4] [2, 2] # same as shape in Numpy
print(x.ndim, y.ndim) # 1 2
print(x.numel(), y.numel()) # 4 4 # same as size in Numpy

tensor([[1, 2],
        [3, 4]])
torch.Size([4]) torch.Size([2, 2])
1 2
4 4


# References
[1] [머신러닝 파이토치 다루기 기초 - WikiDocs](https://wikidocs.net/book/9379)  
[2] [PyTorch Tensor vs NumPy Array - GeeksforGeeks](https://www.geeksforgeeks.org/pytorch-tensor-vs-numpy-array/)  
[3] [torch.tensor — PyTorch 2.4 documentation](https://pytorch.org/docs/stable/generated/torch.tensor.html)  