<a href="https://colab.research.google.com/github/rudevico/Gachon-AISTUDY/blob/main/Pytorch_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. tensor data type
* 기본적으로 Machine Learning에서는 연산 속도를 위해서 array data type을 사용한다.
* 이때 Numpy에서는 CPU를 사용하여 array를 연산하기 때문에 DL 수준의 dataset에 대해서 연산하기에는 시간이 많이 소요된다.
* Tensor는 GPU 연산을 지원하는 array이다. pytorch에서는 이를 사용한다.  

> 왜 Numpy ndarray가 아닌, Pytorch tensor를 사용하는지에 대한 자세한 이유들은 이후 실습 과정을 통해서 자연스럽게 알 수 있을 것으로 판단된다.

## 1. 0. Convert list(python) or ndarray(numpy) to tensor(pytorch)

cf. [torch.tensor — PyTorch 2.4 documentation](https://pytorch.org/docs/stable/generated/torch.tensor.html)

```
torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)
```

**Parameters**  
* __data__ - Can be a list, tuple, Numpy `ndarray`, scalar, ...  

**Keyword Arguements**  
* __dtype__(`torch.dtype`, optinal) - the desired data type of returned tensor. default라면, 원본 데이터 타입
* __device__(`torch.device`, optional) - the device of the constructed tensor. defalut라면, 'cpu' 사용, 'cuda'로 설정 시 gpu 사용 가능.
* __requires_grad__(_bool_, optional)
* **pin_memory**(*bool*, optional)

In [29]:
import torch

# case1-1. python list_int
data = [[1, 2, 3], [4, 5, 6]]

x_default = torch.tensor(data)
x_int = torch.tensor(data, dtype=int)
x_int64 = torch.tensor(data, dtype=torch.int64) # default int
x_int32 = torch.tensor(data, dtype=torch.int32)

# pytorch에서는 int ßßdata type의 default를 64bit로 한다
print(x_default.dtype)
print(x_int.dtype)
print(x_int64.dtype)
print(x_int32.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_default)    # default -> no return
print(x_int)        # default -> no return
print(x_int64)      # default -> no return
print(x_int32)      # not default -> return

torch.int64
torch.int64
torch.int64
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [30]:
# case1-2. python list_float
data = [[1, 2, 3], [4, 5, 6]]

x_float = torch.tensor(data, dtype=float)
x_float32 = torch.tensor(data, dtype=torch.float32) # default float
x_float64 = torch.tensor(data, dtype=torch.float64)
x_double = torch.tensor(data, dtype=torch.double)

# pytorch에서는 int data type의 default를 32bit로 한다
print(x_float.dtype)
print(x_float32.dtype) # default float
print(x_float64.dtype)
print(x_double.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_float)      # not default -> return
print(x_float32)    # default -> no return
print(x_float64)    # not default -> return
print(x_double)     # not default -> return

torch.float64
torch.float32
torch.float64
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [31]:
# case2. numpy to tensor
# 결론적으로는 list to tensor나 ndarray to tensor나 동일하다.
import numpy as np
np_data = np.array(data)
print(type(np_data))
print(np_data)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [32]:
# case2-1. numpy ndarray_int
x_default = torch.tensor(np_data)
x_int = torch.tensor(np_data, dtype=int)
x_int64 = torch.tensor(np_data, dtype=torch.int64) # default int
x_int32 = torch.tensor(np_data, dtype=torch.int32)

# pytorch에서는 int data type의 default를 64bit로 한다
print(x_default.dtype)
print(x_int.dtype)
print(x_int64.dtype)
print(x_int32.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_default)    # default -> no return
print(x_int)        # default -> no return
print(x_int64)      # default -> no return
print(x_int32)      # not default -> return

torch.int64
torch.int64
torch.int64
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [33]:
# case2-2. numpy ndarray_float
data = [[1, 2, 3], [4, 5, 6]]

x_float = torch.tensor(np_data, dtype=float)
x_float32 = torch.tensor(np_data, dtype=torch.float32) # default float
x_float64 = torch.tensor(np_data, dtype=torch.float64)
x_double = torch.tensor(np_data, dtype=torch.double)

# pytorch에서는 int data type의 default를 32bit로 한다
print(x_float.dtype)
print(x_float32.dtype) # default float
print(x_float64.dtype)
print(x_double.dtype)

# pytorch에서는 tensor의 data type이 default가 아닌 경우에만 return한다
print(x_float)      # not default -> return
print(x_float32)    # default -> no return
print(x_float64)    # not default -> return
print(x_double)     # not default -> return

torch.float64
torch.float32
torch.float64
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


## 1. 1. How to use GPU(CUDA)

In [34]:
# torch를 실행중인 device에서 cuda(gpu)를 사용할 수 있는지 확인
cuda_available = torch.cuda.is_available()
print(cuda_available)

True


In [35]:
# torch.tensor() 등으로 tensor를 생성할 때는 default로 'cpu'를 사용
print(x_default.device)

cpu


In [36]:
# CPU에 텐서 생성 (default)
tensor_cpu = torch.tensor([1.0, 2.0, 3.0]) # same as the below
tensor_cpu = torch.tensor([1.0, 2.0, 3.0], device='cpu') # same as the above
print(tensor_cpu.device) # cpu

# GPU에 텐서 생성 (CUDA를 사용할 수 있는 경우)
if torch.cuda.is_available():
    tensor_gpu = torch.tensor([1.0, 2.0, 3.0], device='cuda')
    print(tensor_gpu.device)  # cuda:0
else:
    print('Error: CUDA not available')

cpu
cuda:0


In [37]:
# 기존 텐서를 다른 장치로 이동
tensor_cpu_to_gpu = tensor_cpu.to('cuda')  # CPU에서 GPU로 이동
print(tensor_cpu_to_gpu.device)  # cuda:0

tensor_gpu_to_cpu = tensor_gpu.to('cpu')  # GPU에서 CPU로 이동
print(tensor_gpu_to_cpu.device)  # cpu

cuda:0
cpu


## 1. 2. How to create the tensor

In [38]:
# 1. non-random values

# 1-dim tensor
x = torch.tensor([1, 2, 3])
print(x)
print()

# 2-dim tensor
y = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(y)
print()

# 3-dim tensor, every element is 0
z = torch.zeros((2, 3, 4))
print(z)
print()

# 4-dim tensor, every element is 1
w = torch.ones((2, 2, 2, 2))
print(w)
print()

tensor([1, 2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])



In [39]:
# 2. use the Distribution for random values

# case1. Uniform Distribution
# create 3 by 2 tensor, each element is randomed between [0, 1)
x = torch.rand((3, 2))
print(x)

# case 2. Normal Distribution
# create 2 by 3 tensor, each element is randomed,
# following normal distribution, mean = 0 and deviation = 1
y = torch.randn((2, 3))
print(y)

tensor([[0.2631, 0.4802],
        [0.3996, 0.2660],
        [0.7379, 0.3503]])
tensor([[-0.5243, -1.8474,  0.2482],
        [ 2.3250, -1.4715, -0.3961]])


In [40]:
# 3. randomly-uninitialized values(it is fast because non-intialize)

x = torch.empty(2, 3) # default dtype is float32
print(x)
print(x.dtype)

y = torch.empty(2, 3, dtype=torch.int64) # you can use anoter dtype
print(y)
print(y.dtype)

tensor([[-2.6691e-33,  3.0709e-41, -2.4794e-32],
        [ 3.0709e-41,  7.3790e-01,  3.5029e-01]])
torch.float32
tensor([[137421895495040,  94126540939792,              32],
        [             80,  94140637894011,             129]])
torch.int64


## 1. 3. Convet ndarray to tensor by `.from_numpy()` and `.tensor()`
**1. 0.**에서는 `.tensor()`를 사용해서 numpy array를 tensor로 변환했다.  
`.from_numpy()`로도 변환이 가능한데, 둘의 차이를 알아보자.
```
x_np = np.array([1, 2, 3])
x_tensor = torch.tensor(x_np)
print(type(x_np), type(x_tensor))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
```

```
y_np = np.array([1, 2, 3])
y_tensor = torch.from_numpy(y_np)
print(type(x_np), type(y_tensor))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
```

In [41]:
# `.tensor()`는 call by value 개념이다
# 즉 기존의 ndarray를 copy해서 memory에 별도로 생성한다
# 따라서 tensor와 ndarray는 서로 독립적이다
x_np = np.array([1, 2, 3])
x_tensor = torch.tensor(x_np)
print('ndarray:', x_np[0], 'tensor:', x_tensor[0])

# tesnor의 element를 바꿔도 ndarray에는 영향을 주지 않는다
x_tensor[0] = -1
print('ndarray:', x_np[0], 'tensor:', x_tensor[0])

ndarray: 1 tensor: tensor(1)
ndarray: 1 tensor: tensor(-1)


In [42]:
# `.from_numpy()`는 call by reference 개념이다
# 이미 ndarray가 할당된 memory adress가 존재할 때,
# `.from_numpy()`로 생성된 tensor 객체는 ndarray와 동일한 address를 referencing한다
y_np = np.array([1, 2, 3])
y_tensor = torch.from_numpy(y_np)
print('ndarray:', y_np[0], 'tensor:', y_tensor[0])

# tesnor의 element를 바꾸면 ndarray에도 영향을 준다
y_tensor[0] = -1
print('ndarray:', y_np[0], 'tensor:', y_tensor[0])

# 반대의 경우에도 마찬가지
y_np[1] = -2
print('ndarray:', y_np[1], 'tensor:', y_tensor[1])

ndarray: 1 tensor: tensor(1)
ndarray: -1 tensor: tensor(-1)
ndarray: -2 tensor: tensor(-2)


### 1. 3.(검증) memory address 확인을 통한 검증

In [43]:
# 처음에 내가 아는 선에서 시도한 검증은 다음과 같이 `id()`를 사용하는 것이었다
print(id(x_np), id(x_tensor)) # predict: different  | actual: different
print(id(y_np), id(y_tensor)) # predict: different  | actual: different

137417068456976 137417068960144
137417068457264 137417068962864


> numpy와 tensor 모두 memory address에 value 자체를 보관하고, **그 address를 참조하는 객체**를 생성하는 것이다.  

> 즉 value 자체의 address와 참조하는 객체의 address 두 가지가 존재하는 상태이다.  
이때 `id()`는 후자를 리턴한다.  

> (다음 cell) 다음과 같이 **value 자체의 address**를 확인할 수 있다.

In [44]:
# predict: different    | actual: different
print(x_np.__array_interface__['data'][0])
print(x_tensor.data_ptr())
print()
# predict: same         | actual: same
print(y_np.__array_interface__['data'][0])
print(y_tensor.data_ptr())

94126506241600
94126539663808

94126506241792
94126506241792


## 1. 4. Convert tensor to ndarray
tensor 객체를 Numpy ndarray로 변환하는 method는 `tensor.numpy()` method 뿐이다.  

또한 `tensor.numpy()`는 copy하지 않고, 무조건 share한다.

In [45]:
x_npnp = x_tensor.numpy()
print(type(x_npnp))

y_npnp = y_tensor.numpy()
print(type(y_npnp))

print(x_np.__array_interface__['data'][0])
print(x_tensor.data_ptr()) # x_np를 copy한 x_tensor
print(x_npnp.__array_interface__['data'][0]) # x_tensor를 share한 x_npnp
print()

print(y_np.__array_interface__['data'][0])
print(y_tensor.data_ptr()) # y_np를 share한 y_tensor
print(y_npnp.__array_interface__['data'][0]) # y_tensor를 share한 y_npnp

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
94126506241600
94126539663808
94126539663808

94126506241792
94126506241792
94126506241792


# 2. tensor attributes
Pytorch의 **tensor object**는 많은 attributes를 갖지만, 그 중에서 자주 쓸 만한 것들에 대해서만 다루겠다.  
1. __dtype__
    * data type
2. __device__
    * tensor object가 위치한 device(cpu, gpu)
3. __size__
    * tensor object의 shape
4. __ndim__
    * tensor object의 dimension
5. __numel()__
    * tensor object의 전체 elements 수

In [46]:
# 'dtype', 'device'는 위에서 이미 다뤘으므로 생략함
x = torch.tensor([1, 2, 3, 4])
y = x.view(2, 2) # same as reshape in Numpy

print(y) # [[1, 2], [3, 4]]
print(x.size(), y.size()) # [4] [2, 2] # same as shape in Numpy
print(x.ndim, y.ndim) # 1 2
print(x.numel(), y.numel()) # 4 4 # same as size in Numpy

tensor([[1, 2],
        [3, 4]])
torch.Size([4]) torch.Size([2, 2])
1 2
4 4


# 3. tensor calculation
Numpy와 마찬가지로 **Broadcasting**이 적용된다.

In [47]:
# addition in tensor
a = torch.tensor([[1, 2,], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
var_add = a + b
print(var_add)

tensor([[ 6,  8],
        [10, 12]])


In [48]:
# subtraction in tensor
var_sub = a - b
print(var_sub)

tensor([[-4, -4],
        [-4, -4]])


In [49]:
# multiply in tensor
var_mul = a * b
print(var_mul)

tensor([[ 5, 12],
        [21, 32]])


In [50]:
# divide in tensor
var_div = a / b
print(var_div)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In mathematics, particularly in linear algebra, matrix multiplication is a binary operation that produces a matrix from two matrices. For matrix multiplication, **the number of columns in the first matrix** must be equal to **the number of rows in the second matrix**. The resulting matrix, known as the matrix product, has **the number of rows of the first** and **the number of columns of the second** matrix. The product of matrices A and B is denoted as AB.  
* $C_{11} = A.row_1 * B.col_1$
* $C_{12} = A.row_1 * B.col_2$
* $C_{21} = A.row_2 * B.col_1$
* $C_{22} = A.row_2 * B.col_2$

In [51]:
# matrix multiplication
var_matrix_mul = torch.mm(a, b)
print(var_matrix_mul)

tensor([[19, 22],
        [43, 50]])


In mathematics, the dot product or scalar product is an algebraic operation that **takes two equal-length sequences of numbers** (usually coordinate vectors), and **returns a single number**. It is often called the inner product.

In [52]:
# dot product in tensor
var_dot_prod = torch.dot(a[0], a[1])
print(var_dot_prod)

tensor(11)


In [59]:
# max value
#                  col1    col2
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[4, 3], [2, 1]])
var_max_a = torch.max(a)
var_max_b = torch.max(b)
var_max_ab = torch.max(a, b)
print(var_max_a, var_max_b) # 4 4
# column끼리 비교해서 max를 리턴함
# max_col1, max_col2
print(var_max_ab) # [4, 3], [3, 4]

tensor(4) tensor(4)
tensor([[4, 3],
        [3, 4]])


In [65]:
# dimensionality reduction; 차원 축소
a = torch.tensor([[1, 2], [3, 4]])

# dim=0, 하나의 matrix의 각 row를 개별 matrix로 취급하여 dot product를 수행하는 개념
var_reduce_dim0 = torch.sum(a, dim=0)
# dim=1
var_reduce_dim1 = torch.sum(a, dim=1)

print(var_reduce_dim0)
print(var_reduce_dim1)

tensor([4, 6])
tensor([3, 7])


In [71]:
# transpose
a = torch.tensor([[1, 2], [3, 4]])
# parameter is input tensor, first dim and second dim to transposed
var_trans = torch.transpose(a, 0, 1)
print(var_trans)

tensor([[1, 3],
        [2, 4]])


In [80]:
# indexing
#                   0       1       2
#                  0  1    0  1    0  1
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
var_index = a[1, 0]
print(var_index)

tensor(3)


In [81]:
# slicing
var_slice_1 = a[:, :1] # for the all rows, col1 전까지
             # '까지'니까 selected element가 1개라는 것이 보장되지 않음
             # 따라서 2dim으로 리턴
var_slice_2 = a[:, 1] # for the all rows, col1만
            # '만'이니까 selected element가 1개라는 것이 보장됨
            # 따라서 1dim으로 리턴
print(var_slice_1)
print(var_slice_2)

tensor([[1],
        [3],
        [5]])
tensor([2, 4, 6])


In [82]:
# boolean indexing
a = torch.tensor([1, 2, 3, 4, 5])
# statement 만족하면 True, 아니면 False가 되고 True인 index의 elements만 리턴
var_bool = a[a > 3]
print(var_bool)

tensor([4, 5])


# References
[1] [머신러닝 파이토치 다루기 기초 - WikiDocs](https://wikidocs.net/book/9379)  
[2] [PyTorch Tensor vs NumPy Array - GeeksforGeeks](https://www.geeksforgeeks.org/pytorch-tensor-vs-numpy-array/)  
[3] [torch.tensor — PyTorch 2.4 documentation](https://pytorch.org/docs/stable/generated/torch.tensor.html)  